PS-1553 Refactor so the workspace handling
keboola/workspace-provider pull request #3
Opened 2021-03-30 15:38 UTC by joker806

PS-1553 Refactor so the workspace handling logic & workspace data are independent and existing workspace can be reused

* pridana podpora pro reuse existujiciho workspace
* oddelena reprezentace workspace (`Workspace/*`) od reseni, kde/jak ziskat informace o workspace (`RemoteWorkspaceProviderFactory`)
* rozdeleny `ProviderInitializer` na separatni tridy pro input a output, puvodni `ProviderInitializer` zachovan jako adapter pro BC

2021-03-30 19:53 UTC, odinuv commented on src/Workspace/Local/LocalWorkspace.php
> +class LocalWorkspace implements LocalWorkspaceInterface
To bude zmatený název, protože workspace právě local není :) Nešlo by LocalStaging ?

2021-03-31 07:09 UTC, joker806 commented on src/Workspace/Local/LocalWorkspace.php
> +class LocalWorkspace implements LocalWorkspaceInterface
Urcite by slo.. a abych mozna rovnou zkratil diskuzi, nedostaneme se tim k tomu, ze cela ta knihovna se prejmenuje na `staging-provider`? :smile:

2021-03-31 07:12 UTC, odinuv commented on src/Workspace/Local/LocalWorkspace.php
> +class LocalWorkspace implements LocalWorkspaceInterface
klidně!

2021-03-31 07:18 UTC, odinuv commented on src/Workspace/Local/LocalWorkspace.php
> +class LocalWorkspace implements LocalWorkspaceInterface
Hele radši to 3x přejmenuju teď dokud se to používá na jednom místě než někdy potom, až se to bude používat na 6 místech

2021-04-01 14:26 UTC, joker806 commented on src/Workspace/Local/LocalWorkspace.php
> +class LocalWorkspace implements LocalWorkspaceInterface
Tak jsem s tim trochu zamichal, mrkni jestli to dava vetsi smysl nebo zda by to neslo jetse vylepsit. Pokud by to byl spravny smer, prejmenoval bcyh teda na konec jeste cele repo na `staging-provider` (nebo nejaly jeste lepsi napad? :))

2021-04-01 16:15 UTC, odinuv commented on src/Workspace/Local/LocalWorkspace.php
> +class LocalWorkspace implements LocalWorkspaceInterface
no to je aspoň diff :) To si budu muset projít v klidu.

2021-04-01 18:31 UTC, joker806 commented on src/Workspace/Local/LocalWorkspace.php
> +class LocalWorkspace implements LocalWorkspaceInterface
Neboj, vetsina jsou prazdny radky ;) Kazdopadne neboj se to radne okomentovat, je to moje prvni vetsi vec, tak at si hezky nastavim boundaries.

2021-04-03 21:26 UTC, odinuv requested changes
Tak bohužel, zjistil jsem, že to nefunguje a asi za to můžu já, protože ses tak nějak ptal jestli může být input a output oddělený a on nemůže. 
Zkusil jsem to tady updatnout https://github.com/keboola/docker-bundle/pull/560 a problém je v tom, že tak jak je to teď tak ten OutputProviderInitalized vrátí jinej workspace než InputProviderInitializer. Což je blbé, protože potom se runner snaží udělat OM z workspacu jiného než do kterého dělal IM. Otázka je jestli to vadí data-loaderu (z hlavy bych řekl, že ne). Takže by se to možná dalo (a mělo) řešit tak, že IM ten workspace umožní zjistit a OM ho dostane zadaný a bude tam ta závislost explicitní.

2021-04-06 06:13 UTC, joker806 commented on src/OutputProviderInitializer.php
> +        if (!$stagingFactory instanceof OutputStrategyFactory) {
Jj, to je jen fail-safe, protoze ta OM staging factory dedi z IM. Nevim presne proc, asi tam bude nejaky hacek :) ale idealni by bylo je rozdelit je.

2021-04-06 06:16 UTC, joker806 commented on src/Provider/ABSWorkspaceProvider.php
> -
:thinking: prejmenovat v Gitu? Tohle je normalne presunuty

2021-04-06 06:22 UTC, joker806 commented on src/StagingProvider.php
> +        if ($this->staging !== null) {
To je early return pattern https://medium.com/swlh/return-early-pattern-3d18a41bba8

2021-04-06 06:24 UTC, joker806 commented on src/AbstractProviderInitializer.php
> +     * @param class-string<WorkspaceStagingInterface> $workspaceClass
Tady to bohuzel zatim nema pridanou hodnotu, ale jakmile se zbavime PHP 5.6 a pujde nasadit rozumne aktualni PHPStan, bude to hezky pohlidany :)

2021-04-06 08:52 UTC, odinuv commented on src/AbstractProviderInitializer.php
> +     * @param class-string<WorkspaceStagingInterface> $workspaceClass
vím, ale nevěděl jsem že existuje `class-string`

2021-04-06 08:54 UTC, odinuv commented on src/StagingProvider.php
> +        if ($this->staging !== null) {
vím, jen mi přijde divný ho aplikovat na lazy inicializaci

2021-04-06 08:55 UTC, odinuv commented on src/Provider/ABSWorkspaceProvider.php
> -
jj, přejmenovat v gitu, ale přijde mi, že phpstorm tohle dělá automaticky

2021-04-06 10:53 UTC, joker806 commented on tests/Unit/StagingProviderTest.php
> +            'url' => getenv('STORAGE_API_URL'),
jo, ja byl zvykly, ze testy jsou nejak obviously rozdeleny na rychly loklani testy (unit), ktery si proste muzu out-of-the-box pustit kdykoliv chvi a dojedou za par sekund vs. pomaly testy s nejakyma externima zavislostma (integracni), ktery poustim tak maximalne selektivne, podle toho, co menim a kompletni run nechavam na CI.. ale jde jen o zvyk

2021-04-06 10:55 UTC, joker806 commented on tests/Unit/Staging/RemoteWorkspaceTest.php
> +        yield [SnowflakeWorkspaceStaging::class, 'snowflake'];
no jde k tomu dat klic, stejne jako kdyz mas dataProvider klasickym polem, jestli to je to, co mas na mysli

```
return [
    'test snowflake` => [SnowflakeWorkspaceStaging::class, 'snowflake'],
];
```

by melo byt stejne jako

```
 yield 'test snowflake` => [SnowflakeWorkspaceStaging::class, 'snowflake'];
```

2021-04-06 10:59 UTC, joker806 commented on tests/Unit/StagingProviderTest.php
> +        self::assertSame(1, $callCounter, 'Check getter was called once after getWorkspaceId');
hmm.. rikal jsem si, ze pokud by neco nefungovalo, bude jasnejsi, na cem konkretne se to pokazilo (proto jsme tam i pridaval ty messages), ale tohle je uz misto, kde nevim, protoze nemam tolik natestovano, takze muzu klidne zjednodusit na toto?

```
$workspaceProvider->getWorkspaceId();
$workspaceProvider->getWorkspaceId();
$workspaceProvider->getCredentials();
self::assertSame(1, $callCounter, 'Check getter is called at most once within any method');
```

2021-04-06 11:00 UTC, joker806 commented on src/WorkspaceProviderFactory/ExistingWorkspaceProviderFactory.php
> +class ExistingWorkspaceProviderFactory implements WorkspaceProviderFactoryInterface
:+1: doplnim

2021-04-06 11:01 UTC, joker806 commented on src/Staging/Workspace/WorkspaceStaging.php
> +            throw new \InvalidArgumentException(sprintf(
zadnej konkretni.. upravim

2021-04-06 11:03 UTC, joker806 commented on tests/Integration/Provider/AbsWorkspaceProviderTest.php
> +
Jo, na SYNAPSE related testy jsme myslim nesahal. Hele a napadlo me uz nejsou prave k podobnym vecem urceny test groupy?

2021-04-06 14:43 UTC, odinuv commented on tests/Unit/Staging/RemoteWorkspaceTest.php
> +        yield [SnowflakeWorkspaceStaging::class, 'snowflake'];
tak jestli to funguje :)

2021-04-06 14:44 UTC, odinuv commented on tests/Unit/StagingProviderTest.php
> +        self::assertSame(1, $callCounter, 'Check getter was called once after getWorkspaceId');
good necháme tak

2021-04-07 14:02 UTC, joker806 commented on src/ProviderInitializer.php
> +     * @deprecated use OutputProviderInitializer directly
Odstraneno

2021-04-07 14:03 UTC, joker806 commented on tests/Unit/StagingProviderTest.php
> +            'url' => getenv('STORAGE_API_URL'),
Zrusil jsme teda po domluve ty separatni namespaces

2021-04-07 14:35 UTC, joker806 commented on tests/Unit/Staging/RemoteWorkspaceTest.php
> +        yield [SnowflakeWorkspaceStaging::class, 'snowflake'];
funguje

![Screenshot from 2021-04-07 16-35-14](https://user-images.githubusercontent.com/271753/113884479-4b220300-97bf-11eb-98fb-f695e0fb2ec6.png)

2021-04-07 14:50 UTC, joker806 commented on tests/Integration/Provider/AbsWorkspaceProviderTest.php
> +namespace Keboola\WorkspaceProvider\Tests\Integration\Provider;
No, tady me ted napda, je to k cemu by ten test mel patrit? Puvodni trida `AbsWorkspaceProvider` se rozdelila na:
* `AbsWorkspaceStaging` ktery resi nejaky objektovy zapouzdreni array dat podle typu workspace
* univerzalni `StagingProvider`, ktery neni zavisly na typu workspace

A ono kdyz ted premyslim nad obsahem toho testu, tak jestli to spravne chapu, tak vlastne testuje:
* ze se workspace zalozil na Storage API (`$workspace = $workspaces->getWorkspace($workspaceId)` - coz je uz testovane v
* ze se data (credentials) z API spravne mapuji skrze provider (`$provider->getCredentials()`) - coz je uz testovane v `Keboola\WorkspaceProvider\Tests`

Neni tim padem vlastne v pohode tenhle test uplne zrusit? Stejny pripad potom je `SynapseWorkspaceProviderTest`

2021-04-08 06:43 UTC, joker806 commented on tests/Integration/Provider/AbsWorkspaceProviderTest.php
> +
:+1:  upraveno

2021-04-08 06:43 UTC, joker806 commented on src/WorkspaceProviderFactory/ExistingWorkspaceProviderFactory.php
> +class ExistingWorkspaceProviderFactory implements WorkspaceProviderFactoryInterface
doplneno

2021-04-08 08:04 UTC, joker806 commented on src/AbstractProviderInitializer.php
> +        $workspacesApiClient = new Workspaces($this->stagingFactory->getClientWrapper()->getBasicClient());
hmm.. co je ujety?

2021-04-08 11:09 UTC, odinuv commented on src/AbstractProviderInitializer.php
> +        $workspacesApiClient = new Workspaces($this->stagingFactory->getClientWrapper()->getBasicClient());
ujetý je, že localprovider vyžaduje zadání workspaces klienta

2021-04-08 11:31 UTC, joker806 commented on src/AbstractProviderInitializer.php
> +        $workspacesApiClient = new Workspaces($this->stagingFactory->getClientWrapper()->getBasicClient());
No vidis, to mi vubec necvaklo :bulb: to by melo byt easy vyresit

2021-04-08 12:02 UTC, joker806 commented on src/AbstractProviderInitializer.php
> +        $workspacesApiClient = new Workspaces($this->stagingFactory->getClientWrapper()->getBasicClient());
rozdelil jsem ten `StagingProvider` na `LocalStagingProvider` a `WorkspaceStagingProvider` s patricnyma zavislostma.

2021-04-08 12:19 UTC, pivnicek commented
:-) I will need to take a little time with it
![image](https://user-images.githubusercontent.com/569139/114025459-6b13fe00-9875-11eb-870e-e19324477052.png)

2021-04-08 12:23 UTC, pivnicek commented on src/AbstractProviderInitializer.php
> +     * @param class-string<WorkspaceStagingInterface> $workspaceClass
oooh, ja taky ne! 👍

2021-04-08 12:25 UTC, joker806 commented
Yeah, sorry for that.. started with a small change to be able to reuse existing workspaces and ended with nearly complete rewrite of the code :(

2021-04-08 12:35 UTC, pivnicek commented
no worries at all, I like what I see so far!

2021-04-08 13:48 UTC, pivnicek reviewed
wow.  took a while for that getter business to sink into my thick head, but I got it eventually :-) nice work.

I'll check it out locally to see it all together now

2021-04-08 13:48 UTC, pivnicek commented on tests/Provider/LocalStagingProviderTest.php
> +        $workspacesApiClient->expects(self::never())->method(self::anything());
I'm not sure if this is being used at all?  doesn't seem like it, but I could be missing something

2021-04-08 13:48 UTC, pivnicek commented on tests/Provider/LocalStagingProviderTest.php
> +        $workspacesApiClient->expects(self::never())->method(self::anything());
likewise I'm not sure this gets used

2021-04-08 14:05 UTC, odinuv commented on tests/Provider/LocalStagingProviderTest.php
> +        $workspacesApiClient->expects(self::never())->method(self::anything());
what do you mean? it checks that it's not used

2021-04-08 14:09 UTC, joker806 commented on tests/Provider/LocalStagingProviderTest.php
> +        $workspacesApiClient->expects(self::never())->method(self::anything());
Oh.. I it was originally used (or more precisely, required but not used) and I forgot the mock there after last round of refactoring. Will remove..

2021-04-08 16:00 UTC, pivnicek commented on tests/CombinedProviderInitializerTest.php
> +        // TODO how to test?
not sure, what exactly do you want to test here?

2021-04-08 20:36 UTC, odinuv reviewed
hele ja myslim, ze dobry, ještě by to chtělo fixnout tyhle errory https://github.com/keboola/workspace-provider/pull/3/commits/331a80b187aaa66915a26108bebf96f6b56a4a72 a pokud se ti bude líbit, tak ten test https://github.com/keboola/workspace-provider/pull/4

2021-04-08 20:36 UTC, odinuv commented on tests/Provider/LocalStagingProviderTest.php
> +        self::assertSame(1, $callCounter, 'Check getter is called at most once within any method');
Tak můžem to ještě párkrat zkusit zavolat, ale myslím, že se ten výsledek nezmění :D

2021-04-08 20:36 UTC, odinuv commented on tests/Provider/LocalStagingProviderTest.php
> +        self::assertSame($localPath, $workspaceProvider->getPath());
někam by se mělo přihodit, že se na localstaging dá zavolat cleanup()

2021-04-09 06:35 UTC, joker806 commented on src/Provider/AbstractStagingProvider.php
> +     */
Jednodussi urcite :) ale ne tak presny (kdyz budeme uvazovat, ze by byl nasazeny aktualni PHPStan/Psalm/...)

2021-04-09 06:41 UTC, joker806 commented on tests/Provider/LocalStagingProviderTest.php
> +        self::assertSame($localPath, $workspaceProvider->getPath());
Nebyl jsme si tim jisty, protoze v podstate na to nejde udelat assertion. Ale uz jsem nasel `@doesNotPerformAssertion` :)

2021-04-09 07:07 UTC, joker806 commented on tests/CombinedProviderInitializerTest.php
> +        // TODO how to test?
I discussed that briefly with Odin, he put something together in https://github.com/keboola/workspace-provider/pull/4

2021-04-09 07:10 UTC, joker806 commented on src/Provider/ABSWorkspaceProvider.php
> -
Nikdy jsme to nijak spesl neresil, tak si nejsem jisty. Mam to jeste proverit/zkusit preskladat nebo si to jen priste vic hlidat?

2021-04-09 07:11 UTC, joker806 commented on tests/Integration/Provider/AbsWorkspaceProviderTest.php
> +namespace Keboola\WorkspaceProvider\Tests\Integration\Provider;
@odinuv co myslis?

2021-04-09 07:12 UTC, joker806 commented on src/InputProviderInitializer.php
> +                InputStrategyFactory::WORKSPACE_ABS => new Scope([Scope::TABLE_METADATA]),
Should I do something about it? Or was it just a side note and we can resolve the conversation? :)

2021-04-09 07:32 UTC, joker806 commented
@odinuv ohledne https://github.com/keboola/workspace-provider/commit/331a80b187aaa66915a26108bebf96f6b56a4a72, jak by si to videl?
* easy way je proste pridat do vsech testu spravny data a spolihat na to, ze tam nikdo nebude rvat nevalidni data
* proper way je pridat do tech staging trid validaci vsech dat

Proc jsem na vazkach je, aby to melo nejakou hlavu a patu.. nikde jinde jsem moc nevidel, ze by se resila nejaka validace dat o kterych se "vi", ze prichazi z API response. A osobne bych v delsim horizontu spis navrhoval, aby uz ty API client tridy (`Components`, `Workspaces` apod.) provadely mapping na objekty a nepredavaly se jen tak volne pole.

2021-04-09 08:39 UTC, odinuv commented
jednoznačně easy way.

Na to musíme spolíhat, že to API vrací to co má (což se testuje na straně API), to bysme se totálně zamrdali v nekonečných kontrolách. Tady jde opravdu jen o to, aby tam nelítaly notices v testech.

2021-04-09 08:42 UTC, odinuv commented on src/Provider/ABSWorkspaceProvider.php
> -
příště

2021-04-09 08:43 UTC, odinuv commented on src/Provider/ABSWorkspaceProvider.php
> -
tady jsou to stejně pár řádkový třídy, o nic nejde

2021-04-09 08:43 UTC, odinuv commented on src/InputProviderInitializer.php
> +                InputStrategyFactory::WORKSPACE_ABS => new Scope([Scope::TABLE_METADATA]),
side note :)

2021-04-09 08:45 UTC, odinuv commented
A jak píšeš, tohle je v dlouhodobým horizontu práce SAPI klienta a ne te appky, která ho používá

2021-04-09 10:24 UTC, odinuv commented on tests/Integration/Provider/AbsWorkspaceProviderTest.php
> +namespace Keboola\WorkspaceProvider\Tests\Integration\Provider;
njn pravda, je takovej zbytečnější, asi se nebudu zlobit, když tam nebude

2021-04-09 10:26 UTC, odinuv commented on tests/Provider/LocalStagingProviderTest.php
> +        self::assertSame($localPath, $workspaceProvider->getPath());
jj, ona je to taková podivná metodata (ale potřebujem ji tam). Taky se dá napsat `assertTrue(true)`

2021-04-09 11:42 UTC, joker806 commented on tests/Integration/Provider/AbsWorkspaceProviderTest.php
> +namespace Keboola\WorkspaceProvider\Tests\Integration\Provider;
ok, odstraneno

2021-04-09 11:57 UTC, pivnicek approved these changes
tak za mne je to celkove dobry 👍 ,  necham to na Vas

2021-04-09 12:18 UTC, odinuv approved these changes
mám k tomu jedinou věc - zapiš někam (buď do readme, ale spíš radši do confluence), co tahle knihovna dělá a proč je naimplementovaná tak jak je naimplementovaná a jak se používá.

2021-04-09 15:11 UTC, merged